data:
  nr_folds: 5
  train_percentage: 0.9
 
instance_selection:
  percentage_keep: 0.75
  cores: -1
  batch_size: 80
  num_reads: 200
  random_state: 123
  sleep: 3

network_model:
  batch_size: 32
  epochs: 10
  lr: 0.00005 
  patience: 5




